version: "3"
services:
  fec-web:
    image: registry-vpc.cn-hongkong.aliyuncs.com/fec/web:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    env_file:
      - stack.env
    networks:
      static-network:
        ipv4_address: 10.0.0.9
networks:
  static-network:
    external: true