// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "organization",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "" },
      { name: "creationTime", type: "datetime" },
      { name: "description", type: "text" },
      { name: "logoUrl", type: "text" },
      { name: "coverUrl", type: "text" },
      { name: "website", type: "text" },
      { name: "contactMail", type: "email" },
      { name: "status", type: "text", notNull: true, defaultValue: "" },
      { name: "slug", type: "string", unique: true },
      { name: "twitter", type: "string" },
      { name: "weibo", type: "string" },
      { name: "qqGroup", type: "string" },
      { name: "bilibili", type: "string" },
    ],
  },
  {
    name: "event",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "" },
      { name: "startDate", type: "datetime" },
      { name: "endDate", type: "datetime" },
      { name: "city", type: "string", notNull: true, defaultValue: "" },
      { name: "address", type: "string" },
      { name: "website", type: "string" },
      { name: "logoUrl", type: "string" },
      { name: "coverUrl", type: "multiple" },
      { name: "organization", type: "link", link: { table: "organization" } },
      { name: "slug", type: "string", notNull: true, defaultValue: "" },
      { name: "detail", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Organization = InferredTypes["organization"];
export type OrganizationRecord = Organization & XataRecord;

export type Event = InferredTypes["event"];
export type EventRecord = Event & XataRecord;

export type DatabaseSchema = {
  organization: OrganizationRecord;
  event: EventRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://JiPai-s-workspace-srsnmc.us-east-1.xata.sh/db/FEC",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
